blank_issues_enabled: false
contant_links:
  - name: Start a new discussion
    url: https://github.com/Bluenix2/wumpy/discussions
    about: All bug reports and feature requests start as discussions, then they get converted to issues.
