site_name: Wumpy
site_description: Documentation for the Discord API wrapper Wumpy
site_author: Bluenix

repo_url: https://github.com/wumpyproject/wumpy
repo_name: GitHub
edit_uri: tree/main/docs

docs_dir: 'source'

theme:
  name: material
  palette:
    scheme: discord  # Custom scheme
    primary: blurple
    accent: blurple
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra_css:
  - css/_extra.css
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Start page:
    - index.md

  - Setting up the bot:
    - setup/index.md
    - Creating the Bot: setup/creating-the-bot.md
    - Authenticatin with Discord: setup/authenticating.md
    - Running the Bot: setup/running-the-bot.md

  - Basic Tutorial:
    - tutorial/index.md
    - Your first command: tutorial/hello-world.md
    - Subcommands: tutorial/nested-hellos.md
    - Command options: tutorial/options.md
    - Optional options: tutorial/optional-options.md
    - Context Menus:
      - Message commands: tutorial/context-menus/message-commands.md
      - User commands: tutorial/context-menus/user-commands.md
    - Option choices: tutorial/rock-paper-scissors.md
    - Multiple options: tutorial/mcdonalds-order.md
    - Enum options: tutorial/choices-with-enums.md
    - Advanced options: tutorial/advanced-options.md
    - Link buttons: tutorial/link-buttons.md
    - Extensions:
      - Extensions FAQ: tutorial/extensions/extensions-faq.md
      - Getting started: tutorial/extensions/simple-example.md
      - Advanced usage: tutorial/extensions/advanced-usage.md

  - Reference:
    - Application commands: reference/interactions/commands.md
    - Utils: reference/utils.md

plugins:
  - search: {}
  - mkdocstrings:
      custom_templates: docs/templates/
      enable_inventory: true
      handlers:
        python:
          selection:
            new_path_syntax: true
            inherited_members: true
          rendering:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            members_order: source
