site_name: Wumpy
site_description: Documentation for the Discord API wrapper Wumpy
site_author: Bluenix

repo_url: https://github.com/Bluenix2/wumpy
repo_name: GitHub
edit_uri: tree/main/docs

docs_dir: 'source'

theme:
  name: material
  palette:
    scheme: discord  # Custom scheme
    primary: blurple
    accent: blurple
  features:
    - content.code.annotate
extra_css:
  - css/_extra.css
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Setting up the bot:
    - setup/index.md
    - setup/creating-the-bot.md
    - setup/authenticating.md
    - setup/running-the-bot.md

  - Basic Tutorial:
    - tutorial/index.md
    - tutorial/hello-world.md
    - tutorial/nested-hellos.md
    - tutorial/options.md
    - tutorial/optional-options.md
