name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'library/**'
      - 'tests/**'

  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
      - reopened
    paths:
      - '.github/workflows/**'
      - 'library/**'
      - 'tests/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Flake8
        run: pip install flake8

      - name: Lint codebase with Flake8
        run: flake8 library/

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
  
      - name: Install Isort
        run: pip install isort

      - name: Verify import order
        run: isort . --check-only

  pyright:
    runs-on: ubuntu-latest
    strategy:
      # If one of the subpackages fail this step, we want to continue running
      # the rest as to not mask errors.
      fail-fast: false
      matrix:
        subpackage:
          - cache
          - bot
          - gateway
          - interactions
          - models
          - rest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Attempt to access cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # The subpackage isn't included here because it should be shared
          key: 'pyright-v3.7'

      - name: Install Pyright and Flit
        run: pip install pyright flit

      - name: Install all subpackages
        run: |
          cd library/
          for subpackage in ${{ env.subpackages }}; do
            cd wumpy-$subpackage/
            flit install
            cd ..
          done
          cd ..

      - name: Verify wumpy-${{ matrix.subpackage }} types
        run: pyright --verifytypes wumpy/${{ matrix.subpackage }}/
