name: Run unit tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'library/**'
      - 'tests/**'

  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
      - reopened
    paths:
      - '.github/workflows/**'
      - 'library/**'
      - 'tests/**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      # If one of the Python versions fail we still want to continue testing
      # the rest if possible.
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    env:
      # This is ordered from lowlevel to toplevel, such that any subpackages
      # that depend on other subpackages are installed last (so that it isn't
      # installed from PyPI).
      subpackages: 'gateway rest models cache interactions bot'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Attempt to access cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: 'test-cache-v${{ matrix.python-version }}'

      - name: Install Pytest and flit
        run: pip install pytest flit

      - name: Install wumpy-testing utility
        run: pip install git+https://github.com/wumpyproject/wumpy-testing

        # If we're unsuccessful in installing wumpy-testing because it is
        # currently broken or similar we can still run all other tests because
        # it is an optional dependency.
        continue-on-error: true

      - name: Install all subpackages
        run: |
          cd library/
          for subpackage in ${{ env.subpackages }}; do
            cd wumpy-$subpackage/
            flit install --extras all
            cd ..
          done
          cd ..

      - name: Run pytest tests
        run: pytest tests/
